// jobApp.model.js
/*
    Stores the Job App Schema used to create the Job App Model for Job App Documents in MongoDB
*/


const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// userId: The User ID generated by mongoDB
// token: The verification token that we generate and send via email to confirm email and also reset password
// createdAt: The data it was created and how long the document expires in
const verificationSchema  = new Schema({
    userId: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    token: {
        type: String,
        required: true
    },
    createdAt: {
        type: Date,
        default: Date.now,
        expires: '24'
    }
});

module.exports = mongoose.model('Verification', verificationSchema);